spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    #data-username: root
    #data-password: 123456
    username: root
    password: 123456
#家里
#    url: jdbc:mysql://192.168.10.240/sell?characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
    url: jdbc:mysql://192.168.87.128/sell?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
  jackson:
    default-property-inclusion: non_null
server:

  servlet:
    context-path: /sell
  port: 8080
wechat:
# 公众号 女王绝美水果捞
  mpAppId: wx9c82b28
  mpAppSecret: adfbbae75718f8

#测试公众号
#  mpAppId: wx51aff1c2551f9f9e
#  mpAppSecret: c63473b5f9c39572ade7c31bd6819287
#商户号
  mchId: 1496314772
#  商户密钥
  mchKey: 1234567899888

#  keyPath: http://app-all.b0.upaiyun.com/01d3059e868cedea3b361b2ad1c05254.p12
  keyPath: F:/03-学习总结/Springboot学习总结/cert/apiclient_cert.p12

  notifyUrl: http://sellasmjne.natapp1.cc/sell/pay/notify


#logging:
#  pattern:
#    console: "%d - %msg%n"
#    file: "%d - %msg%n"
#  path: /var/log/tomcat
#  file: F:/var/log/sell/sell.log
#  level:
#    com.imooc.sell.LoggerTest: debug
